
[env:esp32dev] # [env:esp32c3]
platform = espressif32
board =  esp32dev  # esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

lib_deps = 
    ESP32Async/AsyncTCP
    ESP32Async/ESPAsyncWebServer
    bblanchon/ArduinoJson

debug_tool = esp-prog
debug_init_break = tbreak setup
