// ---------------------------------------------------------------------------
// FX du wagon
// Ajouter un FX = UNE SEULE LIGNE ci-dessous
// ---------------------------------------------------------------------------
// Format : FX_ENTRY(NOM_INTERNE, "nom_json", fonction)
// ---------------------------------------------------------------------------

FX_ENTRY(FEU_ARRIERE,        "feu_arriere",        appliquerLedArriere)
FX_ENTRY(LUMIERE_INTERIEURE, "lumiere_interieure", appliquerLedInterieure)
FX_ENTRY(SERVO_PORTE,        "servo_porte",        appliquerServoPorte)
